<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="assets/js/jquery-3.3.1.min.js"></script>
<script src="assets/js/popper.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/jquery.flexslider.js"></script>
<script src="assets/js/jquery-ui.js"></script>
<script src="assets/js/wow.min.js"></script>
<script>
    new WOW().init();
</script>
<script src="assets/js/main.js"></script>
</body>
</html>